### PR TITLE
Be able to use word at cursor in treesitter query

### PR DESCRIPTION
**Pull request by desdic**
In some queries it would be nice if I could use the word under the cursor as a variable

### CODE REVIEW

**Comment by ziontee113** [comment]
Hi @desdic , thank you for the PR. Can you please add some documentation on how to configure / use this new feature? Thank you very much.

**Comment by desdic** [comment]
Sure I'll add some examples on it later today :)

**Comment by desdic** [comment]
I have added documentation and a example under the lua example :)

**Comment by ziontee113** [comment]
Thank you @desdic. Very interesting feature idea 👍

**Pull request merged**
