### PR TITLE
feat: added highlight groups for color scheme usage

### PR DESCRIPTION
**Pull request by theSafdarAwan**
Hello, @ziontee113. I have added the highlight groups for the neo-minap window i think some people will find it easier to configure the UI appearance of the neo-minimap , if highlight groups were exposed. Thanks.

### CODE REVIEW

**Comment by theSafdarAwan** [comment]
Any way, advanced user can override these highlight groups using the `win_opts.winhl` option. But some people don't know these options deeply so this is an easier way for those user to change highlight groups. And also color schemes can integrate these groups easily.

**Comment by theSafdarAwan** [comment]
I didn't remove the `hl_group` in the `setup_defaults` opts after adding the `NeoMinimapLineNr` hl. Maybe deprecate the `hl_group` opt.

**Comment by ziontee113** [comment]
> advanced user can override these highlight groups using the win_opts.winhl option. But some people don't know these options deeply so this is an easier way for those user to change highlight groups. And also color schemes can integrate these groups easily.

This statement helped me a lot. Thank you very much for your hard work :+1:

**Comment by theSafdarAwan** [comment]
> h

Thanks for creating this amazing.

**Pull request merged**
